Experiment 9 -> Friedman Test on Iris Dataset

In [ ]:
import pandas as pd
import scipy.stats as stats
df = pd.read_csv('/content/Iris_Data.csv')

In [ ]:
sepal_len_setosa = df.loc[df['species']=='Iris-setosa', 'sepal_length'].to_numpy()
sepal_len_versicolor = df.loc[df['species']=='Iris-versicolor', 'sepal_length'].to_numpy()
sepal_len_virginica = df.loc[df['species']=='Iris-virginica', 'sepal_length'].to_numpy()

In [ ]:
sepal_len_setosa

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. ])

In [ ]:
sepal_len_versicolor

array([7. , 6.4, 6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. ,
       6.1, 5.6, 6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6,
       6.8, 6.7, 6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6,
       5.5, 5.5, 6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7])

In [ ]:
sepal_len_virginica

array([6.3, 5.8, 7.1, 6.3, 6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8,
       5.7, 5.8, 6.4, 6.5, 7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2,
       6.2, 6.1, 6.4, 7.2, 7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. ,
       6.9, 6.7, 6.9, 5.8, 6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

3 groups - iris setosa, iris versicolor, iris virginica

Ho = no difference in the mean sepal_length of three groups

Ha = Difference in the mean sepal_length of three groups 

In [ ]:
#perform the friedman test 
stats.friedmanchisquare(sepal_len_setosa, sepal_len_versicolor, sepal_len_virginica)

FriedmanchisquareResult(statistic=73.78571428571435, pvalue=9.498077769131953e-17)

P-value of 9.49 is greater than 0.05, hence rejecting null hypothesis